version: '3.8'

services:
  backend:
    build: ./backend
    container_name: reddao_backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    networks:
      - reddao-net

  frontend:
    build: ./frontend
    container_name: reddao_frontend
    ports:
      - "8080:80" 
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - reddao-net

networks:
  reddao-net:
    driver: bridge
